const ACTIONS = {
    USER_LOGS_IN: 'USER_LOGS_IN',
    USER_LOGS_OUT: 'USER_LOGS_OUT',
    ADD_INFO_TO_CURRENT_USER: 'ADD_INFO_TO_CURRENT_USER',
    SET_ELEMENT_TO_EDIT: 'SET_ELEMENT_TO_EDIT',
    ADD_ELEMENTS_TO_CODE: 'ADD_ELEMENTS_TO_CODE',
    RESET_ALL_WEBSITE_INFORMATION: 'RESET_ALL_WEBSITE_INFORMATION',
    CHNAGE_ELEMENT_CLASS_NAME: 'CHNAGE_ELEMENT_CLASS_NAME',
    UPDATE_CODE_AND_CODEBLOCKS: 'UPDATE_CODE_AND_CODEBLOCKS',
}

export default ACTIONS