const ACTIONS = {
    USER_LOGS_IN: 'USER_LOGS_IN',
    USER_LOGS_OUT: 'USER_LOGS_OUT',
    ADD_INFO_TO_CURRENT_USER: 'ADD_INFO_TO_CURRENT_USER',
    SET_ELEMENT_TO_EDIT: 'SET_ELEMENT_TO_EDIT',
    CLEAR_ALL_WEBSITE_INFORMATION: 'CLEAR_ALL_WEBSITE_INFORMATION'
}

export default ACTIONS