const ACTIONS = {
    USER_LOGS_IN: 'USER_LOGS_IN',
    USER_LOGS_OUT: 'USER_LOGS_OUT',
    ADD_INFO_TO_CURRENT_USER: 'ADD_INFO_TO_CURRENT_USER',
    CREATING_NEW_WEBSITE:'CREATING_NEW_WEBSITE',
    EDIT_WEBSITE_CODE: 'EDIT_WEBSITE_CODE',
    EDIT_WEBSITE_STRUCTURE: 'EDIT_WEBSITE_STRUCTURE',
    SET_ELEMENT_TO_EDIT: 'SET_ELEMENT_TO_EDIT',
    ADD_NEW_ELEMENT: 'ADD_NEW_ELEMENT',
    CHANGE_ELEMENT_CLASS: 'CHANGE_ELEMENT_CLASS',
    STRUCTURE_DND_CHANGE: 'STRUCTURE_DND_CHANGE',
    CONTAINER_ORDER_DND_CHANGE: 'CONTAINER_ORDER_DND_CHANGE',
    ADD_WEBSITE_CONTAINER: 'ADD_WEBSITE_CONTAINER',
    ADD_NEW_COMPONENT: 'ADD_NEW_COMPONENT',
    UPDATE_ALL_WEBSITE_INFORMATION: 'UPDATE_ALL_WEBSITE_INFORMATION',
    CLEAR_ALL_WEBSITE_INFORMATION: 'CLEAR_ALL_WEBSITE_INFORMATION'
}

export default ACTIONS